## Pandas


*   Pandas to najpopularniejsza biblioteka do manipulacji i analizy danych tabularycznych w pythonie
*   Bazuje ona na znanym nam już NumPy
*   Zaprojektowana w celu pracy na **ustrukturyzowanych** danych jak tabele (pliki CSV, arkusze excela itp.).




**Wskazówka Big Data:** Należy pamiętać, że Pandas jest świetnym narzędziem do *analizy* danych, ale niekoniecznie do inżynierii na wielką skalę. Rzeczywiste dane produkcyjne zwykle żyją w relacyjnych bazach danych SQL (np. PostgreSQL) lub NoSQL (np. Cassandra). Z Pandas interface'ujemy się z nimi za pomocą bibliotek takich jak `sqlalchemy` czy `cassandra-driver`. Co więcej, Pandas ładuje całe dane do pamięci RAM komputera. W Big Data, gdy dane są zbyt duże, korzystamy ze środowisk rozproszonych jak **PySpark** lub **Dask** o podobnym API ale zdolnych do przetwarzania terabajtów informacji.

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

## **Dwiema bazowymi** strukturami danych wykorzystywanych przez pandas są:


1.   Series - Jednowymiarowa tablica mogąca przechowywać dowolny typ danych (jak lista)
2.   DataFrame - Dwuwymiarowa **tabelaryczna struktura danych** (tabular data structure) składająca się z rzędów i kolumn, które są obiektami **Series**. Najprościej w świecie mówiąc, zwykła tabelka 🙂

## Series
Czyli jednowymiarowa indeksowana tablica.

Może zostać stworzona zarówno na podstawie pythonowej listy

In [53]:
series = pd.Series([1,2,3,4,5,6,7,8])
series

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

Jak i tablicy ndarray

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
series = pd.Series(np.arange(10))
series

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

Jak widać posiada ona **osobny, tablico-podobny index**, który jest obiektem typu **pd.Index**

In [6]:
series.index

RangeIndex(start=0, stop=10, step=1)

Index, oczywiście możemy definiować własnoręcznie

In [7]:
custom_index_series = pd.Series([1, 2, 3, 4, 5],
                 index = ['index1', 'index2', 'index3', 'index4', 'index5'])
custom_index_series

index1    1
index2    2
index3    3
index4    4
index5    5
dtype: int64

Do poszczególnych elementów możemy dobierać się po ich indeksie, podając go w nawasiach klamrowych

```python
series[index]
```

lub po kropce

```python
series.index
```

In [8]:
custom_index_series['index1'], custom_index_series.index2

(np.int64(1), np.int64(2))

pd.Series jest to więc zbiór par **index: value**, co oczywiście może nam przypominać słownik, co za tym idzie można go wykorzystać do utworzenia Series.

In [9]:
dict_series = pd.Series({'key1': 'Value1',
                         'key2': 'Value2',
                         'key3': 'Value3',
                         'key4': 'Value4',
                         'key5': 'Value5'})
dict_series.name = 'Values' # za pomocą pola name możemy nazwać naszą serię
dict_series

key1    Value1
key2    Value2
key3    Value3
key4    Value4
key5    Value5
Name: Values, dtype: object

Indeksowanie Series odbywa się w praktycznie identyczny sposób jak indeksowanie ndarray, oraz normalnych list

In [10]:
series[0:4]

0    0
1    1
2    2
3    3
dtype: int64

In [11]:
custom_index_series['index2':]

index2    2
index3    3
index4    4
index5    5
dtype: int64

In [12]:
dict_series['key2': 'key4']

key2    Value2
key3    Value3
key4    Value4
Name: Values, dtype: object

Z istotnych rzeczy to jeśli przy tworzeniu Series jaki indeks podamy inty, to nie zostana zostaną one posortowane, zostało zmienione, czyli teraz jak podamy tak jest.

In [13]:
pd.Series({2: 'Value2', 1: 'Value1', 4: 'Value4'})

2    Value2
1    Value1
4    Value4
dtype: object

Oczywiście nadal można to zmienić ręcznie.

In [14]:
pd.Series({2: 'Value2', 1: 'Value1', 4: 'Value4'}, index=[1, 2, 4])

1    Value1
2    Value2
4    Value4
dtype: object

Podsumowując **Series** to praktycznie ta sama jednowymiarowa tablica numpy (**ndarray**) z dodatkiem edytowalnego indeksu.

Szybkie porównanie:

| Cechy                       | Pandas Series                              | NumPy ndarray                           |
|-----------------------------|--------------------------------------------|-----------------------------------------|
| **Typ danych**               | Może przechowywać dane różnych typów       | Zwykle przechowuje dane jednego typu    |
| **Indeksowanie**             | Ma etykiety (indeksy) dla każdego elementu | Indeksowanie tylko za pomocą pozycji    |
| **Operacje**                 | Operacje są wyrównywane na podstawie indeksów | Operacje są wykonywane element po elemencie według pozycji |
| **Obsługa brakujących danych**| Obsługuje brakujące dane (`NaN`)           | Obsługa tylko dla danych typu float |
| **Wydajność**                | Zbudowane na bazie NumPy, więc podobna szybkość | Bardzo zoptymalizowane do danych numerycznych |
| **Metadane**                 | Zawiera etykiety (indeksy)                 | Brak metadanych (czysty numeryczny zbiór danych) |

## DataFrame (Ramka Danych)
Podstawowy obiekt którym będziemy się bawić w Pandas. Jest tym samym czym ndarray jest dla numpy, czyli sercem całem biblioteki. Przechowywać w niej będziemy różne dane tabelaryczne, gdzie każdy rząd nazywany będzie **Observation** (obserwacja), lub **Sample** (próbka), natomiast kolumna nazywana jest **Feature** (cecha), rzadziej **Variable** (zmienna).

In [15]:
df = pd.DataFrame({'Imie': ['Bartek', 'Kamil', 'Miłosz', 'Patrycja'],
                   'Wiek': [25, 26, 23, 26],
                   'Wzrost': [170., 181.5, 177., 160.]})

Pole **colunns** dataframe to dodatkowy atrybut/pole przechowujący nazwy kolumn. Jest to obiekt **index** więc możemy odwoływać się do poszczególnych kolumn po ich nazwie, podobnie jak z indeksami.

In [16]:
df.columns

Index(['Imie', 'Wiek', 'Wzrost'], dtype='object')

In [17]:
 df['Wiek']

0    25
1    26
2    23
3    26
Name: Wiek, dtype: int64

Do poszczególnych kolumn może również odwoływać się po .

Stwarza to jednak problemy gdy nazwy kolumn mają spacje.

In [18]:
df.Wzrost

0    170.0
1    181.5
2    177.0
3    160.0
Name: Wzrost, dtype: float64

Jak wcześniej wspominałem, DataFrame to kolekcja obiektów **series** więc z każdego z nich można utworzyć nową kolumnę.

In [19]:
bd_series = pd.Series({0: '17.01.1999',
                         1: '24.04.1998',
                         2: '12.06.2001',
                         3: '24.03.1998',
                       })

Pandas wykorzystuje numpy'owe typy **datetime64** and **timedelta64** o których oczywiście (jeszcze) nie wspomniałem.

In [20]:
df['Data Urodzenia'] = pd.to_datetime(bd_series, dayfirst = True)

In [21]:
df

       Imie  Wiek  Wzrost Data Urodzenia
0    Bartek    25   170.0     1999-01-17
1     Kamil    26   181.5     1998-04-24
2    Miłosz    23   177.0     2001-06-12
3  Patrycja    26   160.0     1998-03-24

In [22]:
df['Waga'] = pd.Series({0: 76,
                         1: 97,
                         2: 76,
                         3: 62,
                       })
df

       Imie  Wiek  Wzrost Data Urodzenia  Waga
0    Bartek    25   170.0     1999-01-17    76
1     Kamil    26   181.5     1998-04-24    97
2    Miłosz    23   177.0     2001-06-12    76
3  Patrycja    26   160.0     1998-03-24    62

Nowe kolumny możemy również tworzyć na podstawie innych kolumn.

In [23]:
df['BMI'] = df['Waga'] / (df['Wzrost'] / 100)**2 # Broadcasting operacji matematycznych działa tak samo jak w numpy
df

       Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI
0    Bartek    25   170.0     1999-01-17    76  26.297578
1     Kamil    26   181.5     1998-04-24    97  29.445469
2    Miłosz    23   177.0     2001-06-12    76  24.258674
3  Patrycja    26   160.0     1998-03-24    62  24.218750

Można też kolumny usuwać za pomocą metody **drop(columns = [kolumny do usunięcia], inplace = False)** gdzie za pomocą argumentu columns wskazujemy które kolumny chcemy usunąć, a inplace czy DataFrame zostanie zapisana czy nie (False - nie, default)

In [24]:
df.drop(columns = ['Waga', 'Wzrost'], inplace = False)

       Imie  Wiek Data Urodzenia        BMI
0    Bartek    25     1999-01-17  26.297578
1     Kamil    26     1998-04-24  29.445469
2    Miłosz    23     2001-06-12  24.258674
3  Patrycja    26     1998-03-24  24.218750

Wykorzystanie **np.where**, która sprawdza podany warunek i zwraca wartości w zależności czy jest on spełniony czy nie. Jest jeszcze parę funkcji numpy o których nie wspomniałem, będę o nich wspominał w razie potrzeby, jak tutaj.

In [25]:
df['Klasa_wagowa'] = np.where(df['BMI'] >= 25.0, 'Grubas', 'Nie Grubas')
df

       Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI Klasa_wagowa
0    Bartek    25   170.0     1999-01-17    76  26.297578       Grubas
1     Kamil    26   181.5     1998-04-24    97  29.445469       Grubas
2    Miłosz    23   177.0     2001-06-12    76  24.258674   Nie Grubas
3  Patrycja    26   160.0     1998-03-24    62  24.218750   Nie Grubas

Przed usuwaniem kolumn, dla bezpieczeństwa zawsze dobrze jest stworzyć kopię zapasową naszych danych, zwłaszcza jeśli wykonywaliśmy na nich już jakieś operacje czyszczenia danych, dodawania kolumn itp. Kopię najprościej stworzyć kopiując DataFrame metodą **copy**.

In [26]:
df_backup = df.copy()
df.drop(columns = ['Wiek', 'Wzrost'], inplace = True)
df, df_backup

(       Imie Data Urodzenia  Waga        BMI Klasa_wagowa
 0    Bartek     1999-01-17    76  26.297578       Grubas
 1     Kamil     1998-04-24    97  29.445469       Grubas
 2    Miłosz     2001-06-12    76  24.258674   Nie Grubas
 3  Patrycja     1998-03-24    62  24.218750   Nie Grubas,
        Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI Klasa_wagowa
 0    Bartek    25   170.0     1999-01-17    76  26.297578       Grubas
 1     Kamil    26   181.5     1998-04-24    97  29.445469       Grubas
 2    Miłosz    23   177.0     2001-06-12    76  24.258674   Nie Grubas
 3  Patrycja    26   160.0     1998-03-24    62  24.218750   Nie Grubas)

I  wracamy do naszych pierwotnych danych.

In [27]:
df = df_backup.copy()

Warto wspomnieć iż jako że o DataFrame możemy myśleć jako o 'wyspecjalizowanym' słowniku, obsługuje on (niektóre) jego metody np.

In [28]:
df.keys()

Index(['Imie', 'Wiek', 'Wzrost', 'Data Urodzenia', 'Waga', 'BMI',
       'Klasa_wagowa'],
      dtype='object')

In [29]:
list(df.items())

[('Imie',
  0      Bartek
  1       Kamil
  2      Miłosz
  3    Patrycja
  Name: Imie, dtype: object),
 ('Wiek',
  0    25
  1    26
  2    23
  3    26
  Name: Wiek, dtype: int64),
 ('Wzrost',
  0    170.0
  1    181.5
  2    177.0
  3    160.0
  Name: Wzrost, dtype: float64),
 ('Data Urodzenia',
  0   1999-01-17
  1   1998-04-24
  2   2001-06-12
  3   1998-03-24
  Name: Data Urodzenia, dtype: datetime64[ns]),
 ('Waga',
  0    76
  1    97
  2    76
  3    62
  Name: Waga, dtype: int64),
 ('BMI',
  0    26.297578
  1    29.445469
  2    24.258674
  3    24.218750
  Name: BMI, dtype: float64),
 ('Klasa_wagowa',
  0        Grubas
  1        Grubas
  2    Nie Grubas
  3    Nie Grubas
  Name: Klasa_wagowa, dtype: object)]

Podobnie jak w przypadku słownika, po DataFrame również możemy iterować. Służy do tego metoda **iterrows**.

In [30]:
for index, row in df.iterrows():
  print(f'Index: {index}\n\nRząd:\n{row}\n\n\n')

Index: 0

Rząd:
Imie                           Bartek
Wiek                               25
Wzrost                          170.0
Data Urodzenia    1999-01-17 00:00:00
Waga                               76
BMI                         26.297578
Klasa_wagowa                   Grubas
Name: 0, dtype: object



Index: 1

Rząd:
Imie                            Kamil
Wiek                               26
Wzrost                          181.5
Data Urodzenia    1998-04-24 00:00:00
Waga                               97
BMI                         29.445469
Klasa_wagowa                   Grubas
Name: 1, dtype: object



Index: 2

Rząd:
Imie                           Miłosz
Wiek                               23
Wzrost                          177.0
Data Urodzenia    2001-06-12 00:00:00
Waga                               76
BMI                         24.258674
Klasa_wagowa               Nie Grubas
Name: 2, dtype: object



Index: 3

Rząd:
Imie                         Patrycja
Wiek                               26
Wzrost                          160.0
Data Urodzenia    1998-03-24 00:00:00
Waga                               62
BMI                          24.21875
Klasa_wagowa               Nie Grubas
Name: 3, dtype: object

# Indeksowanie
Pandas posiada wiele sposbów dostępu do danych po ich indeksach.

Standardowy pythonowski list slicing

In [31]:
df[1:3]

     Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI Klasa_wagowa
1   Kamil    26   181.5     1998-04-24    97  29.445469       Grubas
2  Miłosz    23   177.0     2001-06-12    76  24.258674   Nie Grubas

Zamiast indeksu możemy również podać listę kolumn do których chcemy się dostać.

In [32]:
df[['Wiek', 'Data Urodzenia']]

   Wiek Data Urodzenia
0    25     1999-01-17
1    26     1998-04-24
2    23     2001-06-12
3    26     1998-03-24

Podobnie mamy też indeksowanie logiczne - maskowanie

In [33]:
df[(df['Wiek'] >= 25) & (df['Wzrost'] <= 180)]

       Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI Klasa_wagowa
0    Bartek    25   170.0     1999-01-17    76  26.297578       Grubas
3  Patrycja    26   160.0     1998-03-24    62  24.218750   Nie Grubas

## loc i iloc, czyli indexery
to za ich pomocą najczęściej będziemy się dobierali do danych po indeksach. Są to atrybuty obiektu DataFrame gdzie loc odwołuje się do indeksu jawnego (explicit), czyli tego który my manualnie nadamy, a iloc do domyślnego (implicit), czyli tego wygenerowanego przez pandas, zazwyczaj 0,1,2,3,4...

In [34]:
df.index = ['osoba_01', 'osoba_02', 'osoba_03', 'osoba_04']
df

              Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI Klasa_wagowa
osoba_01    Bartek    25   170.0     1999-01-17    76  26.297578       Grubas
osoba_02     Kamil    26   181.5     1998-04-24    97  29.445469       Grubas
osoba_03    Miłosz    23   177.0     2001-06-12    76  24.258674   Nie Grubas
osoba_04  Patrycja    26   160.0     1998-03-24    62  24.218750   Nie Grubas

In [35]:
df.loc['osoba_02']

Imie                            Kamil
Wiek                               26
Wzrost                          181.5
Data Urodzenia    1998-04-24 00:00:00
Waga                               97
BMI                         29.445469
Klasa_wagowa                   Grubas
Name: osoba_02, dtype: object

In [36]:
df.iloc[1]

Imie                            Kamil
Wiek                               26
Wzrost                          181.5
Data Urodzenia    1998-04-24 00:00:00
Waga                               97
BMI                         29.445469
Klasa_wagowa                   Grubas
Name: osoba_02, dtype: object

List slicing również tutaj działa

In [37]:
df.loc['osoba_01': 'osoba_03']

            Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI Klasa_wagowa
osoba_01  Bartek    25   170.0     1999-01-17    76  26.297578       Grubas
osoba_02   Kamil    26   181.5     1998-04-24    97  29.445469       Grubas
osoba_03  Miłosz    23   177.0     2001-06-12    76  24.258674   Nie Grubas

In [38]:
df.iloc[0:3]

            Imie  Wiek  Wzrost Data Urodzenia  Waga        BMI Klasa_wagowa
osoba_01  Bartek    25   170.0     1999-01-17    76  26.297578       Grubas
osoba_02   Kamil    26   181.5     1998-04-24    97  29.445469       Grubas
osoba_03  Miłosz    23   177.0     2001-06-12    76  24.258674   Nie Grubas

Za pomocą iloc możemy też dostawać się do poszczególnych elementów, np kolumna 2, element 1 (wzrost osoby_02, Kamila)

In [39]:
df.iloc[1, 2]

np.float64(181.5)

Istnieją też zoptymalizowane metody dostępu do pojedynczych elementów, czyli **at** i **iat**. Nie są często wykorzystywane (przynajmniej ja ich nie widziałem) ale warto o nich wiedzieć. Chyba. Można zabłysnąć na rozmowie 👍

In [40]:
df.at['osoba_01', 'Imie'], df.iat[0, 0]

('Bartek', 'Bartek')

Biorąc pod uwagę że **DataFrame** składa się z obiektów **series**, które bazują na tablicy ndarray, można powiedzieć że samo DataFrame to (znacznie) rozszerzona 2-wymiarowa tablica ndarray.

| Cecha                     | Pandas DataFrame                              | NumPy ndarray                               |
|---------------------------|-----------------------------------------------|---------------------------------------------|
| **Wymiarowość**            | 2D (etykietowane wiersze i kolumny)           | Wielowymiarowe (2D lub więcej)              |
| **Typ danych**             | Kolumny mogą mieć różne typy danych           | Zazwyczaj jednorodne (ten sam typ danych)   |
| **Indeksowanie**           | Indeksowanie za pomocą etykiet (wiersze i kolumny) | Indeksowanie za pomocą liczb całkowitych    |
| **Obsługa brakujących danych** | Obsługuje wartości `NaN` dla brakujących danych | `NaN` tylko w tablicach zmiennoprzecinkowych   |
| **Operacje**               | Operacje wektoryzowane i wyrównane na podstawie etykiet | Operacje element po elemencie wg pozycji   |
| **Metadane**               | Wiersze i kolumny posiadają etykiety (index, kolumny) | Brak etykiet (czyste numeryczne tablice)   |

In [41]:
df.values

array([['Bartek', 25, 170.0, Timestamp('1999-01-17 00:00:00'), 76,
        26.29757785467128, 'Grubas'],
       ['Kamil', 26, 181.5, Timestamp('1998-04-24 00:00:00'), 97,
        29.44546896462749, 'Grubas'],
       ['Miłosz', 23, 177.0, Timestamp('2001-06-12 00:00:00'), 76,
        24.258674071946118, 'Nie Grubas'],
       ['Patrycja', 26, 160.0, Timestamp('1998-03-24 00:00:00'), 62,
        24.218749999999996, 'Nie Grubas']], dtype=object)

Możemy ją również Transponować

In [42]:
df.T

,osoba_01,osoba_02,osoba_03,osoba_04
Imie,Bartek,Kamil,Miłosz,Patrycja
Wiek,25,26,23,26
Wzrost,170.0,181.5,177.0,160.0
Data Urodzenia,1999-01-17 00:00:00,1998-04-24 00:00:00,2001-06-12 00:00:00,1998-03-24 00:00:00
Waga,76,97,76,62
BMI,26.297578,29.445469,24.258674,24.21875
Klasa_wagowa,Grubas,Grubas,Nie Grubas,Nie Grubas

## Wartości brakujące
Wartości brakujące w pandas zaznaczane są wartością **np.nan** z numpy ,lub też pythonowkim **None**. Jest wiele sposobów radzenia sobie z wartościami brakującymi jak imputacja, interpolacja, usuwanie kolumn zawierających bardzo dużą ilość brakujących danych. O tym będziemy mówić przy okazji pracy na prawdziwym datasecie.

In [43]:
# szybkie tworzenie testowage dataframe i zastąpienie losowych wartości, wartościamy np.nan
df_missing_vals = pd.DataFrame(np.random.randn(1000, 10), columns = [f'Col_{i}' for i in range(1, 11)]) # np.random.randn zwraca 2d tablice losowych liczb próbkowanych z dystrybucji nornalnej (normal distribution)
random_x_indicies, random_y_indicies = np.random.randint(0, df_missing_vals.shape[0], 100), np.random.randint(0, df_missing_vals.shape[1], 100)
random_x_indicies, random_y_indicies

(array([175, 748, 884, 247, 931, 101, 914,  95, 244, 498, 606, 998, 980,
        639, 701, 924, 292, 826, 777, 259, 707, 651, 249, 574, 817,  76,
        641, 367, 730, 722,  68, 694, 751,  12, 427, 596, 373, 643, 780,
        345, 117, 877, 412, 377, 203, 178, 420, 932, 162,  56, 372, 754,
        270, 543, 371, 543, 570, 692, 159, 426, 829, 697, 402, 861, 872,
        321, 640,  18, 703, 123, 212, 299, 978,  23, 974, 809, 361, 790,
        747, 923, 768, 251, 511, 476, 927,   7, 915, 807, 346,  81, 433,
        208, 456, 120, 320,  14, 452, 944, 604, 690]),
 array([4, 0, 8, 1, 9, 7, 1, 4, 6, 3, 5, 1, 5, 4, 8, 6, 7, 7, 4, 7, 1, 5,
        3, 3, 5, 7, 7, 8, 3, 0, 5, 7, 4, 8, 8, 0, 0, 4, 7, 7, 4, 9, 9, 2,
        9, 2, 9, 7, 2, 5, 9, 3, 1, 0, 4, 0, 5, 3, 1, 6, 0, 8, 8, 5, 0, 0,
        1, 1, 2, 6, 8, 3, 1, 6, 8, 5, 3, 7, 7, 4, 7, 1, 5, 9, 2, 6, 2, 4,
        7, 4, 7, 9, 0, 6, 9, 7, 6, 9, 1, 0]))

In [44]:
df_missing_vals.values[(random_x_indicies, random_y_indicies)] = np.nan
df_missing_vals

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10
0,-0.052837,1.969953,0.430472,0.324425,-0.212394,1.854682,-0.537661,0.387576,-0.967657,0.465138
1,-0.545085,0.317626,0.127129,-0.678570,0.098680,-1.184579,-1.188641,0.521766,-0.195935,-0.207758
2,0.700799,-1.417106,0.210331,0.028237,1.355105,-0.338492,-1.085590,-0.771531,0.045699,-1.960067
3,0.734614,1.554462,-0.168479,0.793207,-1.174477,0.723354,-1.252099,1.313080,-0.995227,1.084556
4,0.771438,0.481981,0.235694,0.253666,0.293463,-0.161606,0.977668,-1.608554,0.637830,-0.499598
...,...,...,...,...,...,...,...,...,...,...
995,0.462224,-1.032378,0.556288,-0.042263,1.351116,-2.384277,-0.334961,0.663817,0.074207,-0.435319
996,-0.390893,-0.489632,0.906395,0.399487,0.137515,-0.349025,0.614971,-1.332133,-3.411108,-1.121055
997,2.161840,0.358961,1.524339,-1.752535,-0.841685,0.235027,0.074317,1.927727,0.405534,-0.654646
998,0.221739,NaN,1.063131,2.031303,-1.159577,-0.996296,-2.465442,0.739711,-0.201840,1.290793
999,0.447707,-1.054673,0.932073,-0.372954,0.357603,-0.566043,-1.393200,1.176669,0.762481,0.798161

Metoda **.isnull()** zwraca maskę w której zaznaczone są wartości brakujące. Następnie są sumowane przez metodę **sum()**. Następnie dzielimy przez ilość rzędów(obserwacji) i mnożymy przez 100, w skrócie liczby procentowy brak każdej kolumny.

In [56]:
df_missing_vals.isnull().sum()

Col_1     10
Col_2     11
Col_3      6
Col_4      8
Col_5     11
Col_6     10
Col_7      8
Col_8     16
Col_9      9
Col_10    10
dtype: int64

Liczymy % brakijących wartości w całym datasecie. Najpierw sumujemy wartości brakujące w rzędach, potem je sumujemy a następnie dzielimy przez rozmiar df i mnożymy razy 100. W wyniku dostajemy 1% wartości brakujących

In [57]:
df_missing_vals.isnull().sum().sum() / (df_missing_vals.shape[0] * df_missing_vals.shape[1]) * 100

np.float64(0.9900000000000001)

Wartości te możemy wypełnić jakąś wartością, np. średnią za pomocą metody **fillna()**.

In [47]:
df_filled_mean = df_missing_vals.copy()
for col in df_filled_mean.columns:
  df_filled_mean[col] = df_filled_mean[col].fillna(df_filled_mean[col].mean())

((df_filled_mean.isnull().sum() / df_filled_mean.shape[0]) * 100)

Col_1     0.0
Col_2     0.0
Col_3     0.0
Col_4     0.0
Col_5     0.0
Col_6     0.0
Col_7     0.0
Col_8     0.0
Col_9     0.0
Col_10    0.0
dtype: float64

Za pomocą metody **interpolate** możemy je wypełnić za pomocą interpolacji, czyli wypełniamy na podstawie pobliskich danych.

In [48]:
df_interpolated = df_missing_vals.copy()
for col in df_interpolated:
  df_interpolated[col] = df_interpolated[col].interpolate()

((df_interpolated.isnull().sum() / df_interpolated.shape[0]) * 100)

Col_1     0.0
Col_2     0.0
Col_3     0.0
Col_4     0.0
Col_5     0.0
Col_6     0.0
Col_7     0.0
Col_8     0.0
Col_9     0.0
Col_10    0.0
dtype: float64

Możemy również po prostu wyrzucić rzędy zawierające brakujące dane za pomocą **dropna()**. Subset wskazuje na podstawie jakich kolumn usuwamy rzędy.

In [49]:
df_dropped_na = df_missing_vals.copy()
df_dropped_na = df_dropped_na.dropna(subset = ['Col_1'])

In [50]:
len(df_missing_vals), len(df_dropped_na)

(1000, 990)

Często zamiast usuwać całe rekordy/obserwacje możemy usuwać same kolumny które mają zbyt dóżą ilość wartości brakujących.

In [51]:
missing_percentage = df_missing_vals.isnull().sum() / len(df_missing_vals) * 100
columns_to_drop = missing_percentage[missing_percentage > 1]
columns_to_drop

Col_2    1.1
Col_5    1.1
Col_8    1.6
dtype: float64

In [52]:
df_dropped_cols = df_missing_vals.copy()
df_dropped_cols.drop(columns = list(columns_to_drop.index), inplace = True)
df_missing_vals, df_dropped_cols

(        Col_1     Col_2     Col_3     Col_4     Col_5     Col_6     Col_7  \
 0   -0.052837  1.969953  0.430472  0.324425 -0.212394  1.854682 -0.537661
 1   -0.545085  0.317626  0.127129 -0.678570  0.098680 -1.184579 -1.188641
 2    0.700799 -1.417106  0.210331  0.028237  1.355105 -0.338492 -1.085590
 3    0.734614  1.554462 -0.168479  0.793207 -1.174477  0.723354 -1.252099
 4    0.771438  0.481981  0.235694  0.253666  0.293463 -0.161606  0.977668
 ..        ...       ...       ...       ...       ...       ...       ...
 995  0.462224 -1.032378  0.556288 -0.042263  1.351116 -2.384277 -0.334961
 996 -0.390893 -0.489632  0.906395  0.399487  0.137515 -0.349025  0.614971
 997  2.161840  0.358961  1.524339 -1.752535 -0.841685  0.235027  0.074317
 998  0.221739       NaN  1.063131  2.031303 -1.159577 -0.996296 -2.465442
 999  0.447707 -1.054673  0.932073 -0.372954  0.357603 -0.566043 -1.393200

         Col_8     Col_9    Col_10
 0    0.387576 -0.967657  0.465138
 1    0.521766 -0.195935 -0.207758
 2   -0.771531  0.045699 -1.960067
 3    1.313080 -0.995227  1.084556
 4   -1.608554  0.637830 -0.499598
 ..        ...       ...       ...
 995  0.663817  0.074207 -0.435319
 996 -1.332133 -3.411108 -1.121055
 997  1.927727  0.405534 -0.654646
 998  0.739711 -0.201840  1.290793
 999  1.176669  0.762481  0.798161

 [1000 rows x 10 columns],
         Col_1     Col_3     Col_4     Col_6     Col_7     Col_9    Col_10
 0   -0.052837  0.430472  0.324425  1.854682 -0.537661 -0.967657  0.465138
 1   -0.545085  0.127129 -0.678570 -1.184579 -1.188641 -0.195935 -0.207758
 2    0.700799  0.210331  0.028237 -0.338492 -1.085590  0.045699 -1.960067
 3    0.734614 -0.168479  0.793207  0.723354 -1.252099 -0.995227  1.084556
 4    0.771438  0.235694  0.253666 -0.161606  0.977668  0.637830 -0.499598
 ..        ...       ...       ...       ...       ...       ...       ...
 995  0.462224  0.556288 -0.042263 -2.384277 -0.334961  0.074207 -0.435319
 996 -0.390893  0.906395  0.399487 -0.349025  0.614971 -3.411108 -1.121055
 997  2.161840  1.524339 -1.752535  0.235027  0.074317  0.405534 -0.654646
 998  0.221739  1.063131  2.031303 -0.996296 -2.465442 -0.201840  1.290793
 999  0.447707  0.932073 -0.372954 -0.566043 -1.393200  0.762481  0.798161

 [1000 rows x 7 columns])